### ISSUE TITLE
Problem with installation using Python 3.11

### ISSUE THREAD

**Issue by Akasiek** [alexpdev/TorrentFile#158]
After using torrentfile (`torrentfile -V` or any other command) for the first time this error comes up:

```powershell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\torrentfile.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\torrentfile\cli.py", line 608, in main
    execute()
  File "C:\Python311\Lib\site-packages\torrentfile\cli.py", line 544, in execute
    rebuild_parser = subparsers.add_parser(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\argparse.py", line 1188, in add_parser
    raise ArgumentError(
argparse.ArgumentError: argument create, edit, info, magnet, recheck, rebuild
: conflicting subparser alias: build
```

Maybe it's an easy fix but I have no idea. Is it something with Python 3.11?

**Comment by alexpdev** [comment]
@Akasiek  what operating system?

**Comment by Akasiek** [comment]
> @Akasiek  what operating system?

Windows 11

**Comment by alexpdev** [comment]
@Akasiek   I identified the issue... patching now.  should be able to download the new release from pypi within an hour.

**Comment by alexpdev** [comment]
@Akasiek  The new version is up on pypi and merged into git master branch.   Thanks for submitting the Issue

**Comment by Akasiek** [comment]
Thank you! I appreciate the effort
