### ISSUE TITLE
Can't create a torrent from a directory

### ISSUE THREAD

**Issue by xwlcn** [alexpdev/TorrentFile#95]
There are two issues:
1. The file name contains Chinese. Torrent created cannot be resolved.
2. If create a torrent from a directory, the torrent file has no file name, like `.torrent`, and the torrent file located in the target directory instead of current work directory.

**Comment by cjjdaq** [comment]
# torrentfile create --meta-version 3 -t http://1337.abcvg.info:80/announce --magnet -o /home/torrent/我是一个测试.this.is.test.txt.torrent /home/mkt/我是一个测试.this.is.test.txt
Hashing Files::   0%|                                                                                                                                                                                                                                                                                                            | 0/1 [00:00<?, ?file/s]Traceback (most recent call last):
  File "/usr/local/bin/torrentfile", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/torrentfile/cli.py", line 591, in main
    main_script()
  File "/usr/local/lib/python3.6/dist-packages/torrentfile/cli.py", line 586, in main_script
    return args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/torrentfile/cli.py", line 168, in create_command
    create_magnet(outfile)
  File "/usr/local/lib/python3.6/dist-packages/torrentfile/cli.py", line 253, in create_magnet
    meta = pyben.load(metafile)
  File "/usr/local/lib/python3.6/dist-packages/pyben/api.py", line 137, in load
    decoded, _ = bendecode(_fd.read())
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 71, in bendecode
    dic, feed = bendecode_dict(bits)
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 145, in bendecode_dict
    match2, rest = bendecode(bits[feed:])
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 71, in bendecode
    dic, feed = bendecode_dict(bits)
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 145, in bendecode_dict
    match2, rest = bendecode(bits[feed:])
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 71, in bendecode
    dic, feed = bendecode_dict(bits)
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 145, in bendecode_dict
    match2, rest = bendecode(bits[feed:])
  File "/usr/local/lib/python3.6/dist-packages/pyben/bencode.py", line 74, in bendecode
    raise DecodeError(bits)
pyben.exceptions.DecodeError: Decoder is unable to interpret <class 'bytes'> type = b'.is.test.txtd0:d6:lengthi10e11:pieces root32:\x196}G\x93\xb9\x08\xa7\xc7v\xa6\xcf\xf2\xbd\xe1q\x8e\xb6\xe6}\xe9s\xc9\x8d\x9e:\x15\xc7\xce\x04\xd6Oeee6:lengthi10e12:meta versioni2e4:name23:\xe6\x88\x91\xe6\x98\xaf\xe4\xb8\x80\xe4\xb8\xaa\xe6\xb5\x8b\xe8\xaf\x95.this.is.test.txt12:piece lengthi16384e6:pieces20:\x1d+LO{\x97\xd3\x8d\x9f M%\xe3\r~\x9a\x8e\xd6\x10\x07e12:piece layersdee'
Hashing Files:: 2file [00:00, 57.31file/s]

**Comment by alexpdev** [comment]
Hello... I have not added support for files with non ascii characters in it yet... It's on my todo list.  

When you make a torrent from a directory ensure you do not have a "/" at the end or it does what you are describing.  This is a bug that will be patched in the next release.  Which will be soon.
